container:
  image: cirrusci/android-sdk:29
env:
  JSON_KEY: ENCRYPTED[4606b68b5edb7474b71a993e6f9676cf57e164bf1a4f53abb32b7f933590ec2022dc3badf92965337de7e548e89a018a]
  JKS_BASE64: ENCRYPTED[8bacf224ea73cac177d1310beb646c5eca63959b408a2aee1addcc0ad780356416cb000e789c6dc799c8223c6a551a64]
  JKS_PASS: ENCRYPTED[476057194f8fd76c97d49f9365913fc61c0ad213f5af25fa6aaeb2c2bfdd177835cf9ffc51c1a79f7cd038636efdaa27]
  GOOGLE_API_KEYS: ENCRYPTED[81126112c14c5ffde390cec776beac7cc73c0d3421c04d2549de715f4c09bd252496e221559e900591b3c592adbe0671]

clean_task_template: &CLEAN_TASK_TEMPLATE
  always:
    cleanup_script:
      - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      - rm -rf ~/.gradle/caches/transforms-1
      - rm -rf ~/.gradle/caches/journal-1
      - if [ -d ~/.gradle/caches ]; then find ~/.gradle/caches -name "*.lock" -type f -delete; fi

check_task:
  only_if: $BRANCH != "deploy"
  gradle_cache:
    folder: ~/.gradle/caches
  setup_script:
    - |
      echo -e "auth_client_id=<client_id>
        auth_client_secret=<secret>
        auth_scope_photos=readonly" > muzeiPhotos/googleapi.properties
  script: ./gradlew --build-cache check
  << : *CLEAN_TASK_TEMPLATE

deploy_task:
  only_if: $BRANCH == "deploy"
  gradle_cache:
    folder: ~/.gradle/caches
  setup_script:
    - echo "$JSON_KEY" > play-dev-xinthink-3e418a168938.json
    - echo "$JKS_BASE64" | base64 --decode > app/upload_key.jks
    - |
      echo -e "store=upload_key.jks
        alias=upload
        pass=$JKS_PASS
        storePass=$JKS_PASS" > app/keystore.properties
    - |
      echo -e "sdk.dir=$ANDROID_HOME
        keystore.props.file=keystore.properties" > local.properties
    - echo "$GOOGLE_API_KEYS" > muzeiPhotos/googleapi.properties
  install_fastlane_script:
    - bundle install && gem env && bundle show fastlane
  script: bundle exec fastlane deploy offline:false --verbose
  << : *CLEAN_TASK_TEMPLATE
