container:
  image: cirrusci/android-sdk:29

check_task:
  # only_if: $BRANCH == "master"
  gradle_cache:
    folder: ~/.gradle/caches
  setup_script:
    - |
      echo -e "auth_client_id=<client_id>
        auth_client_secret=<secret>
        auth_scope_photos=readonly" > muzeiPhotos/googleapi.properties
  script: ./gradlew check
  cleanup_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -rf ~/.gradle/caches/transforms-1
    - rm -rf ~/.gradle/caches/journal-1
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
